# Lab 2 Practice Questions

Tip: when there is no given array or data, you should produce one using NumPy.

### 1.
a. There is a group of five colleagues: Martin, Harry, Jenny, Dan, and Venessa. They are working on a project and mostly communicate through email. For this purpose, they decided they need their own separate address book where they will store their names and respective email id as key-value pairs. Which data structure do you think they should use for this purpose?   

b. Once the address book is created, they want to display the email ids for all of them.
After a while, Dan decides to leave the project and his address needs to be deleted and the total number of remaining contacts displayed. 

c. To replace Dan, a new person named Serena is hired and she needs to be added to the address book.

In [ ]:
# your solution:

addressBook = {
    'Martin': 'martin@gmail.com',
    'Harry': 'Harry@outlook.com',
    'Jenny': 'Jenny@hotmail.com',
    'Dan': 'Dan@hotmail.com',
    'Venessa': 'Venessa@gmail.com'
}

print('\nThere are {} contacts in the address-book\n'.format(len(addressBook)))

for name, address in addressBook.items():
    print('Contact {} at {}'.format(name, address))

# Deleting a key-value pair
del addressBook['Dan']

print('\nAfter deleting Dans contact')
print('\nThere are {} contacts in the address-book\n'.format(len(addressBook)))

# Adding a key-value pair
addressBook['Serena'] = 'Serena@gmail.com'

if 'Serena' in addressBook:
    print("\nThe address for new employee (Serena) is", addressBook['Serena'])

### 2. 

Write a simple function that takes two parameters and prints the maximum value. (without using max function of course! :D)

In [ ]:
# your solution:

def print_max(a, b):
    if a > b:
        print(a, 'is maximum')
    elif a == b:
        print(a, 'is equal to', b)
    else:
        print(b, 'is maximum')

print_max(6, 2)


### 3.

Given a "matter.txt" file that contains some text. Display the contents of the file in such a way that every alternate character is separated by a symbol "#". To achieve this, write a function definition for display() that would display the entire content of the file matter.txt in the desired format.

In [ ]:
# your solution:

def display():
    file = open("./matter.txt") #replace with your location
    data = file.read()
    for letter in data:
        print(letter, end="#")
 
    file.close()
display()




In [ ]:
# Alternatively to add Character after every other letter i.e ( Th#is#)
def disp(path):

  file = open(path) 
  text = file.read()
  processed_text = ""
  for i in range(0, len(text)):
    if i%2 == 0:
      processed_text = processed_text + text[i:i+2]
    else:
      processed_text = processed_text + "#"

  file.close()
  return processed_text

output = disp("/content/matter.txt")
print(output)

### 4.

Given the function below, once executed, what would be the value of the x and why?

In [ ]:
x = 10
 
def func(x):
  print('x is', x)
  x = 2 #here the variable x is declared locally 
  print('Changed local x to', x) #the local variable x affects the value of x inside this function only

func(x)
print('x is still', x) #once outside the function, the local change of the variable x doesn't effect the value of x

What do you think?



### 5.

Given the function below, once executed, what would be the value of the y and why?

In [ ]:
y = 10

def func():
    global y #here the variable y is declared globally
    print('y is', y)
    y = 2 #the global variable y affects the value of y inside this function
    print('Changed y to', y)

func()
print('y is now', y) #the global change of the variable y effects the value of y outside the function as well.

What do you think?

### 6.
Write a program to combine last element with first element of two given ndarray with different shapes.

In [ ]:
import numpy as np
array1 = ['C++','Go','JS',]
array2 = ['Python','Pandas', 'NumPy', 'Matplotlib']

# your solution:
print("Original arrays:")          
print(array1)
print(array2)          
result = np.r_[array1[:-1], [array1[-1]+array2[0]], array2[1:]]   
print("\nAfter Combining:")       
print(result)


# desired output:
# ['C++' 'Go' 'JSPython' 'Pandas' 'NumPy' 'Matplotlib']

### 7.
Write a NumPy program to create a 2x2x2 array with random values.

In [ ]:
# your solution:

import numpy as np
x = np.random.random((2,2,2))
print(x)

# expected output: (Of course your numbers will be different!)
# [[[0.40192136 0.99430226]
#   [0.73737906 0.58672908]]
#  [[0.39025187 0.70587962]
#   [0.36347519 0.21884057]]]

### 8.
Write a program to find elements within range from a given array of numbers.

in this question the range is (7, 20) included!

In [ ]:
import numpy as np
a = np.array([1, 3, 6, 7, 9, 10, 13, 14, 17, 21 , 29])

# your solution:

print("Original array:")
print(a)
result = np.where(np.logical_and(a>=7, a<=20))
print("\nElements within range: index position")
print(result)

# expected output:
# (array([3, 4, 5, 6, 7, 8]),)

### 9.
Write a program to create an array of (4,5) shape and swap column 1 with column 4.

Hint:

<img src="./images/swap.png" alt="Swap" width=250>

In [ ]:
# your solution:

import numpy as np
array_nums = np.arange(20).reshape(4,5)
print("Original array:")
print(array_nums)
print("\nAfter swapping column 1 with column 4:")
array_nums[:,[0,3]] = array_nums[:,[3,0]]
print(array_nums)

### 10.
In this question you're going to use couple of universal functions of Numpy.

a. Write a code to compute the median of flattened given array.

b. Write a code to count number of occurrences of each value in a given array of non-negative integers.

c. Write a code to compute the 80th percentile for all elements in a given array along the second axis.

In [ ]:
import numpy as np
# a. your solution:

x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 =  np.median(x)
print("\nMedian of said array:")
print(r1)


# b. your solution:
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 
print("\nOriginal array:")
print(array1)
print("Number of occurrences of each value in array: ")
print(np.bincount(array1))


# c. your solution:
x = np.arange(12).reshape((2, 6))
print("\nOriginal array:")
print(x)
r1 = np.percentile(x, 80, 1)
print("\n80th percentile for all elements of the said array along the second axis:")
print(r1)
