# Lab 2 Practice Questions

Tip: when there is no given array or data, you should produce one using NumPy.

### 1.
a. There is a group of five colleagues: Martin, Harry, Jenny, Dan, and Venessa. They are working on a project and mostly communicate through email. For this purpose, they decided they need their own separate address book where they will store their names and respective email id as key-value pairs. Which data structure do you think they should use for this purpose?   

b. Once the address book is created, they want to display the email ids for all of them.
After a while, Dan decides to leave the project and his address needs to be deleted and the total number of remaining contacts displayed. 

c. To replace Dan, a new person named Serena is hired and she needs to be added to the address book.

In [1]:
# your solution:


### 2. 

Write a simple function that takes two parameters and prints the maximum value. (without using max function of course! :D)

In [2]:
# your solution:

### 3.

Given a "matter.txt" file that contains some text. Display the contents of the file in such a way that every alternate character is separated by a symbol "#". To achieve this, write a function definition for display() that would display the entire content of the file matter.txt in the desired format.

In [ ]:
# your solution:
# the "matter.txt" is in the data folder on canvas

### 4.

Given the function below, once executed, what would be the value of the x and why?

In [ ]:
x = 10
 
def func(x):
  print('x is', x)
  x = 2
  print('Changed local x to', x)

func(x)
print('x is still', x)

What do you think?



### 5.

Given the function below, once executed, what would be the value of the y and why?

In [ ]:
y = 10
 
def func():
    global y
    print('y is', y)
    y = 2
    print('Changed y to', y)
 
func()
print('y is now', y)

What do you think?

### 6.
Write a program to combine last element with first element of two given ndarray with different shapes.

In [ ]:
import numpy as np
array1 = ['C++','Go','JS',]
array2 = ['Python','Pandas', 'NumPy', 'Matplotlib']

# your solution:



# desired output:
# ['C++' 'Go' 'JSPython' 'Pandas' 'NumPy' 'Matplotlib']

### 7.
Write a NumPy program to create a 2x2x2 array with random values.

In [ ]:
# your solution:





# expected output: (Of course your numbers will be different!)
# [[[0.40192136 0.99430226]
#   [0.73737906 0.58672908]]
#  [[0.39025187 0.70587962]
#   [0.36347519 0.21884057]]]

### 8.
Write a program to find elements within range from a given array of numbers.

in this question the range is (7, 20) included!

In [ ]:
import numpy as np
a = np.array([1, 3, 6, 7, 9, 10, 13, 14, 17, 21 , 29])

# your solution:



# expected output:
# (array([3, 4, 5, 6, 7, 8]),)

### 9.
Write a program to create an array of (4,5) shape and swap column 1 with column 4.

Hint:

<img src="./images/swap.png" alt="Swap" width=250>

In [4]:
# your solution:


### 10.
In this question you're going to use couple of universal functions of Numpy.

a. Write a code to compute the median of flattened given array.

b. Write a code to count number of occurrences of each value in a given array of non-negative integers.

c. Write a code to compute the 80th percentile for all elements in a given array along the second axis.

In [ ]:
import numpy as np
# a. your solution:




# b. your solution:
array1 = [0, 1, 6, 1, 4, 1, 2, 2, 7] 



# c. your solution:


