## Lab 03- Understanding Numpy Arrays and array oprations 
# Solutions

1. Given an array as an inpurt argument, write a function which returns the data type, dimension, shape and size of the array. 
</br> Initialize a 2-d array (like [4,3,2], [9,55,33])

In [118]:
import numpy as np

arr = np.array([[4,3,2], [9,55,33]])

def arr_description(arr):
  description = {}
  description["type"] = arr.dtype
  description["dimension"] = arr.ndim
  description["shape"] = arr.shape
  description["size"] = arr.size

  return description

print(arr_description(arr))

{'type': dtype('int64'), 'dimension': 2, 'shape': (2, 3), 'size': 6}


2. Create a 2-dimensional array with zeros and verify it printing the result using ndim. Also, replace the diagonal elements with 1's.

- Hint: https://numpy.org/doc/stable/reference/generated/numpy.zeros.html

In [119]:
## Solution

two_dimensional = np.zeros((4, 4), dtype=int)

print(two_dimensional)

print("The dimension of the array:", two_dimensional.ndim)
print("Diagonal Elements: ", two_dimensional.diagonal())

np.fill_diagonal(two_dimensional, 1)

print(two_dimensional)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
The dimension of the array: 2
Diagonal Elements:  [0 0 0 0]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


3. Given an array, 
- show first 3 elements
- show elements after the 4th index to the end
- print the middle sub-array from 4th element to the 8th element
- print every other element in a step of 2.

In [120]:
values = np.arange(20)

## Solution
print("First three elements: ", values[:3])
print("Elements after fourth index", values[4:])
print("The middle sub-array from 4th to 8th element:", values[4:8])
print("Every element in the step of 2", values[::2])

First three elements:  [0 1 2]
Elements after fourth index [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
The middle sub-array from 4th to 8th element: [4 5 6 7]
Every element in the step of 2 [ 0  2  4  6  8 10 12 14 16 18]


4. Find the unique values in the array and fetch the index number of the elements which appear at the first of the list if it has duplicates.

In [121]:
arr = np.array([89, 98, 45, 45, 67, 98, 89, 67])

#Solution
uniques = np.unique(arr)

for element in uniques:
  print(element, "=> First appearance in index ", np.where(arr == element)[0][0])

45 => First appearance in index  2
67 => First appearance in index  4
89 => First appearance in index  0
98 => First appearance in index  1


5. In this code below, you'll see the fancy indexing technique which is relative a simple concept to understand.

- Just see how the indexing works and answer the questions.

- Index with negative indexing as the technique shown below. List out the 2nd, 3rd and the 5th element with negative indexing.

In [129]:
# Creating a 8x4 array where each row has the index number as value for all its columns
arr = np.empty((8, 4)) 

for i in range(8):
    arr[i] = i

## Slicing using fancy indexing
# arr[[1,4,5]]

## Solution
arr[[-2,-3,-5]]

array([[6., 6., 6., 6.],
       [5., 5., 5., 5.],
       [3., 3., 3., 3.]])



 6

 . Given the 2D array,
 - Print out the first 2 columns and all the rows.
 - Print out the last two rows from the 2D Array.
 - Last two columns from the 2D Array
 - Middle rows excluding the first and the last
 - Mirrorize the array. Should look like the mirrored version of the given array.

In [123]:
# #Solution

a = np.array([[1, 3, 9, 8, 5, 7], [11, 22, 30, 45, 55, 78], [85, 25, 98, 65, 35, 15], [9, 7, 8, 4, 5, 6]])

print("First 2 columns and all rows:")
print(a[:, 0:2])
print("Last two rows from the 2D Array:")
print(a[1:, :])
print("Last two columns from the 2D Array:")
print(a[:, 4:])
print("Middle rows excluding the first and the last")
print(a[1:3, :])
print("Mirrorized version of the array:")
print(a[:, ::-1])

First 2 columns and all rows:
[[ 1  3]
 [11 22]
 [85 25]
 [ 9  7]]
Last two rows from the 2D Array:
[[11 22 30 45 55 78]
 [85 25 98 65 35 15]
 [ 9  7  8  4  5  6]]
Last two columns from the 2D Array:
[[ 5  7]
 [55 78]
 [35 15]
 [ 5  6]]
Middle rows excluding the first and the last
[[11 22 30 45 55 78]
 [85 25 98 65 35 15]]
Mirrorized version of the array:
[[ 7  5  8  9  3  1]
 [78 55 45 30 22 11]
 [15 35 65 98 25 85]
 [ 6  5  4  8  7  9]]


7. Complete the following function where n is the integer value and returns a 2-D Array of size (n*n) with 1's on the border and 0's on the inside.

In [124]:
#Solution

def func(n):
    twodim = np.ones((n, n))
    twodim[1:-1, 1:-1] = 0
    return twodim

func(10)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

8. Create a function which takes an argument of matrix size (a and b) and returns the diagonal values of the matrix of size specified. The values in the matrix should be in the range of a * b. In addition, after the creation of matrix, each diagonal element should be added with the value of 100.



In [125]:
## Solution
def create_matrix(a, b):
  rng = np.arange(a*b).reshape(a, b)
  np.fill_diagonal(rng, rng.diagonal() + 100)
  return rng.diagonal()

print(create_matrix(5, 5))

[100 106 112 118 124]


9. Create a numpy array and change it to immutable (read only). Read the documentation on the link below and try to change the value after making the array immutable. Understand the error.

- Hint: https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html

In [ ]:
#Solution
immarr = np.ones(100)
immarr.flags.writeable = False

## This now generates error. 
immarr[9] = 9

10. Create two lists and two numpy arrays and populate these with the value of size 10^7 (10000000) [You can use range and arange for this]. Now try to multiply values of each of the two lists and arrays and get a final list and array of multiplied items. Calculate the execution times of each of the multiplication operation.

- What do you find with this execution times?
- How do you define it?

In [127]:
##Solution

import time

first_list = range(10000000)
second_list = range(10000000)
final_list = []

first_np_arr = np.arange(10000000)
second_np_arr = np.arange(10000000)

################################################
start_time = time.time()

## List Multiplication
final_list = [a * b for a, b in zip(first_list, second_list)]

# Calculating Execution Time
print("Execution Time for List:", (time.time() - start_time), "seconds")

#################################################

start_time = time.time()

## List Multiplication
final_np_array = first_np_arr * second_np_arr

# Calculating Execution Time
print("Execution Time for Numpy Array:", (time.time() - start_time), "seconds")

Execution Time for List: 1.7054636478424072 seconds
Execution Time for Numpy Array: 0.021924257278442383 seconds
