## Lab 04 - Exploring Advanced Numpy Functions on Multidimensional 
# Solutions


### Question 01 - 07 is about Sorting, Data Types and Broadcasting

**01.** Print the sorted array of indices of the numpy array [5, -8, 0, 3, 44, 52, 6].

In [6]:
import numpy as np
array1 = np.array([5, -8, 0, 3, 44, 52, 6])

print(np.argsort(array1))

[1 2 3 0 6 4 5]


**02.** Print the 3 smallest elements of the numpy array [5, -8, 0, 3, 44, 52, 6]

In [ ]:
array2 = np.array([5, -8, 0, 3, 44, 52, 6])

# Solution 1
print(np.sort(array2)[:3]) 

# Solution 2
sorted_index_array = np.argsort(array2)
sorted_array = array2[sorted_index_array]
print(sorted_array[:3]) 

: 

**03.** Sort the array a  by the column 1 and print the sorted array. <br>  
    a = [[1, 5, 0],
         [3, 2, 5],
         [8, 7, 6]]

In [8]:
array3 = np.array([[1, 5, 0],
         [3, 2, 5],
         [8, 7, 6]])

print(array3[array3[:,1].argsort()])

[[3 2 5]
 [1 5 0]
 [8 7 6]]


**04.** Sort the given sturctured array based on 'name' and 'age'. Print both resultant arrays.

In [9]:
array4 = np.array([('Bob', 34, 70.0), ('Alice', 38, 55.0)],
       dtype=[('name', (np.str_, 10)), ('age', np.int32), ('weight', np.float64)])

# Sorting according to the name
sorted_by_name = np.sort(array4, order='name')
print('Sorting according to the name', sorted_by_name)

# Sorting according to the age
sorted_by_age = np.sort(array4, order='age')
print('\nSorting according to the age', sorted_by_age)

Sorting according to the name [('Alice', 38, 55.) ('Bob', 34, 70.)]

Sorting according to the age [('Bob', 34, 70.) ('Alice', 38, 55.)]


**05.** Given a numpy array [5, 29, 44, 18, 50]. Check the dtype of this array. Change the dtype of the given object to 'float64'.

    What is the purpose of dtypes in practical implementations?

In [10]:
array5 = np.array([5, 29, 44, 18, 50])
print(array5.dtype)
array5 = array5.astype('float64')
print(array5.dtype)

int64
float64


dtypes is can be really helpful in cleaning of raw data. For example, let, we have a array of 1000 records with mixed data types where the data types present are string, integer. We want to implement a mathematical operation on this array for cleaning purpose. So when we would try to implement, we would encounter an error. this could be avoided, if we knew the data type of the array in the first place.

In [ ]:
array5 = np.array([5, '29', 44, 18, 50])
array5 / 2

In [14]:
print(array5.dtype)
array6 = array5.astype('int64')
print(array6.dtype)

int64
int64


In [15]:
array6 / 2

array([ 2.5, 14.5, 22. ,  9. , 25. ])

**06.** Print the number of zero values in the matrix
                    [[45, 0, 17],
                    [26, 4, 0],
                    [0, 77, 9]]

In [16]:
matrix6 = np.array([[45, 0, 17],
                    [26, 4, 0],
                    [0, 77, 9]])

# Solution 1
print(np.count_nonzero(matrix6 == 0))

# Solution 2
print(matrix6[np.where(matrix6 == 0)].size)

3
3


**07.** Subtract the array b from the array a, such that each item of b subtracts from respective row of a and print the resultant array.
    a = [[3,4,5],[4,5,6],[5,6,7]] and 
    b = [1,1,1]

    Hint: this is an example of Broadcasting

In [17]:
a = np.array([[3,4,5],[4,5,6],[5,6,7]])
b = np.array([1,1,1])

print(a - b[:,None])

[[2 3 4]
 [3 4 5]
 [4 5 6]]


### Question 08 - 11 is about Linear Algebra

##### NumPy Linear Algebra: https://numpy.org/doc/stable/reference/routines.linalg.html#

**08.** Print the transpose of the array. 
       [[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],
       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]]

In [18]:
matrix8 = np.array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# Solution 1
print(matrix8.T)

# Solution 2
print(matrix8.transpose())

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


**09.** Print the sum of the diagonal for the array
                    [[45, 34, 17],
                    [26, 4, 0],
                    [78, 77, 9]]
                    

In [19]:
matrix9 = np.array([[45, 34, 17],        
                    [26, 4, 0],
                    [78, 77, 9]])

# Solution 1
print(np.trace(matrix9)) 

# Solution 2
print(sum(np.diagonal(matrix9)))

58
58


**10.** Print the inner product of the two arrays a and b.
    a = [1,2,3,4,5]
    b = [4,5,6,7,8]

In [20]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

print(np.inner(a, b))

100


**11.** Print the euclidean distance between two arrays a and b.
    a = [1,2,3,4,5]
    b = [4,5,6,7,8]

    Hint1: Euclidean distance is the square root of the sum of the squared difference of each element in the array.
    
    Hint2: There is a library of numpy for calculating functionalities of linear algebra.

In [21]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

# Solution 1
print(np.linalg.norm(a-b))

# Solution 2
a_sub_b = a - b
squared_and_sum = np.dot(a_sub_b.T, a_sub_b)
print(np.sqrt(squared_and_sum))

# Solution 3
sum_sq = np.sum(np.square(a - b))
print(np.sqrt(sum_sq))

6.708203932499369
6.708203932499369
6.708203932499369
