# NumPy: Arrays and Vectorized Computations
## DAT540 Introduction to Data Science
## University of Stavanger
### L05
#### Antorweep Chakravorty (antorweep.chakravorty@uis.no)

In [2]:
# Import required modules
import numpy as np
np.random.seed(1234)

- NumPy dype Hierarchy

<img src='images/ndtypes.png'>

## Broadcasting
  - describes how arithmetic works between arrays of different shapes

<img src='images/broadcastingrule.png'> 

  - Over axis=0

<img src='images/broadcasting1.png' width='350'>

  - Over axis=1

<img src='images/broadcasting2.png' width='350'>

In [3]:
# Broadcasting over axis 0 of 3D array
x = np.arange(24).reshape(2,3,4)
y = np.arange(12).reshape(3,4)
print('x:\n', x)
print('y:\n', y)

x - y

x:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
y:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 0,  0,  0,  0]],

       [[12, 12, 12, 12],
        [12, 12, 12, 12],
        [12, 12, 12, 12]]])

In [6]:
# If we have this array, and perfrom *sum* over axis 0 to get summation over columns, we get this
arr = np.arange(4).reshape(2,2)
print('arr:\n', arr)
print('sum (axis=0) over columns:', arr.sum(axis = 1))

arr:
 [[0 1]
 [2 3]]
sum (axis=0) over columns: [1 5]


In [ ]:
# Lets look at a vector
a = np.arange(4)
print('shape of a:', a.shape)
print('a:', a)
print('sum a over axis 0:', a.sum(axis=0))
  
# let us convert it into 1x4 matrix
b = a.reshape(1,4)
print('\nshape of b: ', b.shape)
print('b:', b)
print('sum b over axis 0:', b.sum(axis=0))
print('sum b over axis 1:', b.sum(axis=1)) 

In [ ]:
# a 2-D array
a = np.arange(4).reshape(2,2)
print('shape of a:', a.shape)
print('a:\n', a)
print('\nsum a over axis 0:', a.sum(axis=0))
print(a[0], '+', a[1], '=', a[0]+a[1]) # How does the operation happen
print('\nsum a over axis 1:', a.sum(axis=1))
print(a[:,0], '+', a[:,1], '=', a[:,0]+a[:,1]) # How does the operation happen

### Class Exercise 
#### What is the shape of this array
```
a:
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
```
#### Calculate the sum over axis=2 and axis=1. What will be their respective shape and dimensions?
#### What is the shape of the following array. Is it possible to broadcast and add the following array to the above array? If yes, good, else transform the above array without dropping any indices or axis, so that you can add the following array to it.
```
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])
```

## Array-Oriented Programming with Arrays
  - The practice of replacing explicit loops with array expressions is commonly referred to as vectorization
  - NumPy arrays allows many kinds of data processing tasks as concise array expressions, rather than using loops
  - Vectorized array operations are one or two (or more) orders of magnitude faster

In [7]:
# Let's say you have two 1-D arrays and you want to evaluate the expression sqrt(x^2 + y^2) 
#  for each element pair in the arrays.
x = np.arange(4) # 1x4
y = np.arange(4, 7, 1) # 1x3
print('x:\n', x)
print('y:\n', y)
result = []
# Traditionally we can use two for loops
for i in y:
  for j in x:
    result.append(np.sqrt(i ** 2 + j ** 2))
result = np.array(result)
print('shape of result:', result.shape) #why?
# We can transform this to a 3x4 array
print('3x4 result\n:', result.reshape(3,4))

x:
 [0 1 2 3]
y:
 [4 5 6]
shape of result: (12,)
3x4 result
: [[4.         4.12310563 4.47213595 5.        ]
 [5.         5.09901951 5.38516481 5.83095189]
 [6.         6.08276253 6.32455532 6.70820393]]


In [8]:
# However, using np.meshgrid we can take two 1D arrays and produce two 2D matrices corresponding to all pairs of (x, y) in the two input arrays
xs, ys = np.meshgrid(x, y) # creates two 3x4 arrays

In [9]:
print('xs:\n', xs)
print('ys:\n', ys)
# Evaluating a function sqrt(x^² + y^²) across a regular grid of values
z = np.sqrt(xs ** 2 + ys ** 2)
z

xs:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
ys:
 [[4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]]


array([[4.        , 4.12310563, 4.47213595, 5.        ],
       [5.        , 5.09901951, 5.38516481, 5.83095189],
       [6.        , 6.08276253, 6.32455532, 6.70820393]])

- Expressing Conditional Logic as Array Operations
- **numpy.where** function is a vectorized version the ternary expression
- What is a ternary expression?

- *x if condition else y*
- If we have two 1-D arrays and we want to choose the maximum element when comparing each element from the two arraysa

In [10]:
x = np.random.randint(1,100,9)
y = np.random.randint(1,100,9)
cond = x > y
print('x:', x)
print('y:', y)
print('cond:', cond)

x: [48 84 39 54 77 25 16 50 24]
y: [27 31 44 31 27 59 93 70 81]
cond: [ True  True False  True  True False False False False]


In [11]:
# Using traditional python scheme, we will do something like this
result = [(x if c else y) for x, y, c in zip(x, y, cond)]
result

[48, 84, 44, 54, 77, 59, 93, 70, 81]

In [12]:
result = np.where(x > y, x, y)
result

array([48, 84, 44, 54, 77, 59, 93, 70, 81])

- The second and third arguments to np.where doesn't need to be array, one or both of them can be scalars
- Suppose you had a matrix of randomly generated data and you wanted to replace all positive values with 1 and all negative values with 0. 
- How do you do this using np.where

In [13]:
x = np.random.randn(4,4)
np.where(x > 0, 1, 0)

array([[0, 1, 1, 1],
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 1]])

In [ ]:
# if we want to retain the original value for all positive values and only change negative values to zero, we can do some thing like this
np.where(x > 0, x, 0)

  - Mathematical and Statistical Methods
    - Computes statistics about an entire array or the data along an axis
    - Aggregations (reductions) such as *sum*, *mean*, and *std* are called using array instance methods or using the top-level NumPy functions
    - Functions like *sum*  and *mean* takes an optional axis argument that computes the statistic over the given axis

<img src='images/reductions.png'>

In [ ]:
x = np.arange(8).reshape(2,2,2)
print('x:\n', x)
print('Array Mean:', x.mean()) # using array instance method
print('Array Sum:', np.sum(x)) # using top-level NumPy functions
print('Array mean over axis=1:\n', x.mean(axis=1))
print('Array sum over axis=0:\n', np.sum(x, axis=0))

In [14]:
x = np.arange(8)
print('Array cumsum:\n', np.cumsum(x, axis=0)) # Whats happening here


Array cumsum:
 [ 0  1  3  6 10 15 21 28]


  - Methods for Boolean Arrays
    - Boolean values are coerced to 1 (True) and 0 (False)
    - Thus, *sum* can be used as a means of counting True values in a boolean array

In [ ]:
x = (np.random.randn(8) > 0)
print('x:\n',x)
print('x.sum():', x.sum())
print('x.any(): ', x.any()) # Checks whether one or more values in an array is True
print('x.all(): ', x.all()) # Checks whether every values in an array is True

 #### **Sorting**
- NumPy arrays can be sorted *in-place* with the sort **instance** method of the array
- Using the top-level **np.sort** method on an array would return a *copy*
- Multidimensional arrays can also be sorted along a axis

In [ ]:
x = np.random.randn(8)
print('x:\n', x)
# Using the instance method. in-place sorting
x.sort()
print('x (sorted):\n', x)

In [ ]:
# Using the top-level np.sort method. sorted copy is returned
np.random.shuffle(x) # in place shuffling
x_out = np.sort(x)
print('x_out:\n', x_out)
print('x:\n', x)
print('\ny:\n', y)

In [ ]:
y = np.random.randint(0, 10, 8).reshape(2,4)
y.sort(axis=0)
print('y.sort(0):\n', y)
y.sort(axis=1)
print('y.sort(1):\n', y)

- Indirect Sorts: argsort and lexsort
- Certain cases requires reordering of datasets by one or more keys. In addition to using the *key* argument in the sort method describing a method for secondary sorting, we can also use the *argsort* array instance method or the top-level *np.lexsort* method
  - an axis can be provided to either of the methods to sort over a given axis
  - *argsort* returns the integer indices of a array after sorting it
  - *lexsort* performs indirect lexicopraphical sort on multiple key arrays
  - in any of the sorting methods, the attribute *kind* can be used to specify the sorting algorithm: 'quick', 'mergesort', or 'heapsort' (default:'kind=quicksort')

In [17]:
# argsort
values = np.array([5, 0, 1, 3, 2]) * 1000
indexer = values.argsort()
print('indexer:', indexer)
print('unsorted values using argsort:', values)
print('sorted values using argsort:', values[indexer])


indexer: [1 2 4 3 0]
unsorted values using argsort: [5000    0 1000 3000 2000]
sorted values using argsort: [   0 1000 2000 3000 5000]


In [ ]:
# lexsort: performing on data identified by first and last names
f_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
l_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Waters'])
sorter = np.lexsort((f_name, l_name))
print('sorter:', sorter)
df = zip(l_name[sorter], f_name[sorter])
print('Sorted Data:\n', list(df))

#### Class Exercise: Sorting a 2-D array rows based on their values in the first column
##### Generate an array of shape 5x4 using randint

- Partially Sorting Arrays could be a way to determine the largest or smallest elements in an array
- *np.partition* and np.argpartition" partitions an array around the k-th smallest element
- np.partition(arr, 3) would result in array with smallest three values in no purticular order as the first 3 elements of the array
-np.argpartition, is similar to argsort and returns the indices that rearranges the data in the equivalent order

#### Partition a 5x4 array using np.partition over kth=3. What happens

    - **np.searchsorted** finds elements in a sorted array
    - performs a binary search on a sorted array identifying the location in the array where a value could be inserted to keep the array sorted
    - An array of values can also be passed, to get an array of indices back
    - search is performed from left to right and returns the index of the first value it finds
    - argument *side='right'* returns the last index of the value it finds

In [29]:
arr = np.array([0, 1, 7, 12, 15])
print('insert 0:', np.searchsorted(arr, 0))
print('insert 1:', np.searchsorted(arr, 1))
print('insert 1:', np.searchsorted(arr, 1, side='right'))
print('insert 100:', np.searchsorted(arr, 100))

insert 0: 0
insert 1: 1
insert 1: 2
insert 100: 5


### **Set Logic**
- NumPy has basic set operations for 1-D arrays
- *np.unique* returns the sorted sorted unique values in an array (copy)
- *np.in1d* returns a boolean array, indicating the membership of one array elements in another 

<img src='images/array_setops.png'>

In [20]:
x = np.random.randint(6, 12,size=12)
y = np.random.randint(4, 14,size=3)
print('x:', x)
print('y:', y)
print('unique:', np.unique(x))
print('nd.in1d:', np.in1d(y, x))

x: [10  9 11 10  8  8 10 10  8  7  9  8]
y: [13 11  8]
unique: [ 7  8  9 10 11]
nd.in1d: [False  True  True]


### **Array Manipulation**
- Reshaping converts an array from one shape to another without *copying*, if the underlying values are contiguous
- tuple is provided to reshape that indicates the new shape
- One of the passed shape dimensions can be *-1*, in which case the value would be inferred
- NumPy arrays are stored in *row major order* (C-order), meaning items in each row of the array are stored in adjacent memory locations.
- Arrays can be also stored in *column major order* (F-order/Fortran), by specifying the *order=F* when creating or reshaping the array

    <img src='images/ndarray_order.png' width='300'>

- The opposite of reshape is *flattening* or *raveling*, that transforms a n-D array into 1-D
- The array instance method *ravel* can be used to flatten an array. Like reshape, ravel doesnot produce a copy of the array if the underlying values are continuous. If we want to instead always create a copy, we would use the array instance method **flatten**


```python
arr = np.arange(10) # a vector
arr1 = arr.reshape(2, -1) # infers -1 as '5'.
```

In [ ]:
x = np.arange(10).reshape(2,5)
x[:,2:4] = -1

print('x:', x) # x reflects the changes from 'y' as reshape of 'y' into z, makes a copy as the order was changed
a = x.ravel(order='C') # make a view
a[0:2] = -9
print('x, after a was changed:', x)

b = y.ravel(order='F') # makes a copy
b[:] = 0
print('x, after b was changed:', x)

### Concatenating and Splitting Arrays
  - *np.concatenate* takes a sequence and joins them together in order along the input axis      
  - *np.split* slices an array into multiple arrays along an axis

<img src='images/array_splits.png' width=350>

In [ ]:
arr1 = np.arange(1, 7, step=1).reshape(2,3)
arr2 = np.arange(7, 13, step=1).reshape(2,3)
print('np.concatenate on axis=0:\n', np.concatenate([arr1, arr2], axis=0))
print('\nnp.concatenate on axis=1:\n', np.concatenate([arr1, arr2], axis=1))      

In [33]:
#Splitting Arrays
arr = np.arange(30).reshape(5,6)
print('arr:\n', arr)
arr1, arr2, arr3 = np.split(arr, [1,3], axis=0)
print('arr1:\n', arr1) # arr[:, 0:2]
print('arr1:\n', arr2) # arr[:, 2:3]
print('arr1:\n', arr3) # arr[:, 3:]

arr:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
arr1:
 [[0 1 2 3 4 5]]
arr1:
 [[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
arr1:
 [[18 19 20 21 22 23]
 [24 25 26 27 28 29]]


- Repeating Elements: tile and repeat
- *repeat* and *tile* array instance and top-level np methods respectivlely that allows repetition​ or replication of arrays to produce larger arrays 
- *repeat* replicates each element in an array to a specified number of times
  - an integer passed to the repeat method repeats each element that number of times
  - multidimensional arrays can have their elements repeated along a axis. If no axis is passed, array is flattened first
  - Similarly an array of integer can be also passed to when repeating a multidimensional array to repeat a given slice a different number of times
- np.tile allows stacking copies of an array along an axis
  - The second argument of the tile method, decribes the number of tiles. A scalar value perfroms tiling row by row. A tuple as the second argument would indicate the layout of the tiling

In [26]:
arr = np.arange(4)
print('arr:', arr)
print('1d repeat(3):', arr.repeat(3))
arr = arr.reshape(2,2)
print('arr:\n', arr)
print('2d repeat(3):\n', arr.repeat(3)) # will flatten the array and then repeat each element
print('2d repeat(3, axis=0):\n', arr.repeat(3, axis=0)) # repeats over rows
print('2d repeat(3, axis=1):\n', arr.repeat(3, axis=1)) # repeats over cols
print('2d repeat([1,3], axis=1):\n', arr.repeat([1,3], axis=1))

arr: [0 1 2 3]
1d repeat(3): [0 0 0 1 1 1 2 2 2 3 3 3]
arr:
 [[0 1]
 [2 3]]
2d repeat(3):
 [0 0 0 1 1 1 2 2 2 3 3 3]
2d repeat(3, axis=0):
 [[0 1]
 [0 1]
 [0 1]
 [2 3]
 [2 3]
 [2 3]]
2d repeat(3, axis=1):
 [[0 0 0 1 1 1]
 [2 2 2 3 3 3]]
2d repeat([1,3], axis=1):
 [[0 1 1 1]
 [2 3 3 3]]


In [34]:
arr = np.arange(4).reshape(2,2)
print('arr:\n', arr)
print('2d tile(2):\n', np.tile(arr, 2))
print('2d tile(2,1):\n', np.tile(arr, (2,1)))
print('2d tile(3,2):\n', np.tile(arr, (3,2)))

arr:
 [[0 1]
 [2 3]]
2d tile(2):
 [[0 1 0 1]
 [2 3 2 3]]
2d tile(2,1):
 [[0 1]
 [2 3]
 [0 1]
 [2 3]]
2d tile(3,2):
 [[0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]
 [0 1 0 1]
 [2 3 2 3]]


- Fancy Indexing Equivalents: **take** and **put**
- *take* and *put* are array instance methods that are useful in special cases of only making a selection on a single axis
- *take* retrives values of an array from a list on indices on a particular axis. If no axis is provided, it retrieves the values from the flattened representation of the array
- *put* updates the values specified with a list of indices in an array. It performs its operations in-place. It takes no axis, rather sets the values on the flattened C-representation of the array

In [35]:
arr = np.arange(10).reshape(2,5) * 100
print('arr:\n', arr)
inds = [7, 1, 7, 6]
print('arr.take([inds]):\n', arr.take([inds]))
arr.put(inds, 42)
print('arr:\n', arr)
print('arr.take([], axis=1):\n', arr.take([2,1,4], axis=1))


arr:
 [[  0 100 200 300 400]
 [500 600 700 800 900]]
arr.take([inds]):
 [[700 100 700 600]]
arr:
 [[  0  42 200 300 400]
 [500  42  42 800 900]]
arr.take([], axis=1):
 [[200  42 400]
 [ 42  42 900]]


### File Input and Output with Arrays
  - NumPy is able to save and load data to and from disk either in text or binary format
  - *np.save* and *np.load* are two workhorse functions for efficiently saving and loading data on disk
  - Arrays are saved by default in an uncompressed raw binary format with file extension *.npy*
  - Multiple arrays can be stored in an uncompressed archive *.npz* file using *np.savez* method and passing the arrays as arguments
  - *np.savez_compressed* method can be used to store the arrays with compression
  - *npz* files are loaded as a dict-like object that loads indivisual arrays lazily

In [ ]:
x = np.arange(100)
y = np.arange(100, 1000)
# the ndarray x will be stored into a file call data.npy
np.save('./data/data', x)
# the ndarrays x and y will be stored into a archive file (with compression) called data.npz
np.savez_compressed('./data/data', x, y)
# lets list our local file system
!ls -l

In [ ]:
a = np.load('./data/data.npy') # Loading data.npy into variable a
b = np.load('./data/data.npz') # Loading data.npz into variable a
print('a:', a[:10])
print('b:\n', b['arr_0'][:10]) # Lazily loading 1st array

  - Memory-Mapped Files is a mechanism to interact with binary data on disk as though it was stored in an in-memory array
  - the NumPy **memmap** object enables small segments of a file to be read and written without reading the whole array into memory
  - *memmap* uses the same methods as in-memory arrays and thus can be substituted into many algorithms where an ndarray would be expected
  - Data in memmap is buffered in memory, but it can be written to disk by calling *flush*
  - Whenever a memmap falls out of scope and is garbage collected, any changes will be flushed to disk.Alternatively, *del* memmap_variable can be used to retire an existing memmap
  - When opening an existing memmap, its *dtype* and *shape* needs to be specified as the file is only a block of binary data
  
  ```python
mmap = np.memmap('filename' dtype='float64', mode='w+', shape=(10000, 10000))
# Slicing a memmap returns a view on data on disk:
section = mmap[:5]
```

- **Linear Algebra**
  - Multiplying two 2-D arrays with *** results in an element-wise product instead of a matrix dot product
  - Instead the *dot* array instance method or top-level *np.dot* method allows matrix multiplication
  - Alternatively, **@** symbol can also be used to perfrom dot product
  - *np.linalg* has a standard set of matrix decompositions methods

 <img src='images/linalg.png' width='350'>

In [ ]:
x = np.random.randint(0, 100, 4).reshape(2,2)
y = np.random.randint(0, 100, 6).reshape(2, 3)
print('x.dot(y):\n', x.dot(y))
print('x @ y:\n', x @ y)


- Structured and Record Arrays
- ndarrays is a *homogeneous* data container
- However, there is a concept of *structured* array that allows representation of hetrogeneous or tablular like data
- A structured ndarray can be created, by providing a list of tuples with (*field_name*, *field_data_type*) for each datatypes that are represented in the array.
- Furthermore, nested dtypes and multidimentional fields could also be created by additionally passing a shape (as an int or tuple) while creating the custom dtype

In [39]:
c_dtype = [('name', np.dtype('U25')), ('age', np.int32), ('height', np.float64)]
df = np.array([('abc', 29, 170.6), ('xyz', 45, 178.0)], dtype=c_dtype)
print('shape', df.shape)
df

shape (2,)


array([('abc', 29, 170.6), ('xyz', 45, 178. )],
      dtype=[('name', '<U25'), ('age', '<i4'), ('height', '<f8')])