In [1]:
%matplotlib qt
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
import numpy as np
import time
import copy


Conway chose his rules carefully, after considerable experimentation, to meet these criteria:

There should be no explosive growth.
There should exist small initial patterns with chaotic, unpredictable outcomes.
There should be potential for von Neumann universal constructors.
The rules should be as simple as possible, whilst adhering to the above constraints.

It is summarized as follows:
1. Any live cell with fewer than two live neighbours dies, as if by underpopulation.
2. Any live cell with two or three live neighbours lives on to the next generation.
3. Any live cell with more than three live neighbours dies, as if by overpopulation.
4. Any dead cell with exactly three live neighbours becomes a live cell, as if by reproduction.

This implies that a
- cell with value 0 become 1, if its neighborhood had 3 live cells
- cell with value 1 becomes 0, if its neighborhood has less than 2 or greater than 3 live cells

In [2]:
# Adds a patch, in this case a rectangle to a matplotlib graph at the specified coordinates and with the stated with and height
def plt_dynamic(x, y, col, ax):     
    ax.add_patch( Rectangle(xy=(x, y), width=1, height=1, angle=0.0, color = col) ) 

In [3]:
from time import sleep

# from IPython.display import display, clear_output # use this if %matplotlib inline is used
# Draws a grid of rectangles that represent the each index of an ndarray
def draw(data, nm, fig, ax):
    # this is any loop for which you want to plot dynamic updates.
    for y in range(nm[1]):    
        for x in range(nm[0]):    
            plt_dynamic(x=x, y=y, col= 'black' if data[x,y] == 1 else 'white', ax=ax)    
    
    # use these if %matplotlib inline is used
    # display(fig)                
    # clear_output(wait=True)
    
    plt.pause(0.1)
    
    
    


In [4]:
# Calculates and generates the next state of an game of life ndarray
def next_gen(data, nm):
    change_map = {}
    for i in range(nm[0]):
        for j in range(nm[1]):
            current_val = data[i][j]
            new_val = -1            
            si = i - 1 if i != 0 else 0
            ei = i + 1 if i < nm[0] - 1 else i
            sj = j - 1 if j != 0 else 0
            ej = j + 1 if j < nm[1] - 1 else j
            neighborhood_rating = data[si:ei+1, sj:ej+1].sum() - current_val            
            if data[i][j] == 0:
                new_val = 1 if neighborhood_rating == 3 else 0
            else:
                new_val = 0 if neighborhood_rating < 2 or neighborhood_rating > 3 else 1       
            
            if current_val != new_val:
                change_map[i, j] = new_val
                
    for ki, kj in change_map:
        data[ki,kj] = change_map[ki,kj]


In [5]:
# Initializes a matplolib graph that will be used to draw a rectangular gird representing conway game of life
def init_canvas(nm):
    fig, ax = plt.subplots(1,1)
    ax.set_xlabel('X') ; ax.set_ylabel('Y')
    ax.set_xlim(0,nm[0]) ; ax.set_ylim(0,nm[1])
    return fig, ax

In [8]:
# A random game of life example
nm = (16,16)
data = np.random.randint(low=0, high=2, size=nm)
data

array([[1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0],
       [1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1]])

In [9]:
try:
    fig, ax = init_canvas(nm)    
    
    while True:    
        draw(data, nm, fig, ax)        
        next_gen(data, nm)                       
except KeyboardInterrupt:
    pass

In [10]:
# Game of life example oscillator
nm = (5,5)
osc = np.zeros(nm)
osc[2,1:4] = 1
osc

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
try:
    fig, ax = init_canvas(nm)
    while True:    
        draw(osc, nm, fig, ax)
        next_gen(osc, nm)        
except KeyboardInterrupt:
    pass

In [12]:
# Game of life example pulser
nm = (15,15)
pulser = np.zeros(nm)
pulser

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [13]:
pulser[1,3:6] = 1
pulser[1,9:12] = 1

pulser[3:6,1] = 1
pulser[3:6,6] = 1
pulser[3:6,8] = 1
pulser[3:6,13] = 1

pulser[6,3:6] = 1
pulser[6,9:12] = 1

pulser[8,3:6] = 1
pulser[8,9:12] = 1

pulser[9:12,1] = 1
pulser[9:12,6] = 1
pulser[9:12,8] = 1
pulser[9:12,13] = 1

pulser[13,3:6] = 1
pulser[13,9:12] = 1


In [14]:
pulser

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [15]:
try:
    fig, ax = init_canvas(nm)
    while True:    
        draw(pulser, nm, fig, ax)
        next_gen(pulser, nm)
except KeyboardInterrupt:
    pass