### File Input and Output with Arrays

1. Create two one dimensional arrays. One array, say a1, has the numbers from 1 to 5 and the other array, say a2,  has the numbers from 5 to 9. The task here is to remove all the numbers in array a1 that are present in array a2. Save the resulted array on the disk. Finally, load the saved array from the disk to see the result.

In [5]:
import numpy as np

In [6]:
#creating two one dimesional arrays
a1 = np.array([1,2,3,4,5])
a2 = np.array([5,6,7,8,9])

#to remove the elements in a1 that are present in a2
result = np.setdiff1d(a1,a2)

#saving the array on the disk
np.save('./data/result_array', result)

#loading the saved array from the disk to see the result
np.load('./data/result_array.npy')

array([1, 2, 3, 4])

2. Load 'Iris.csv' keeping the text intact. Extract a coulmn with sepal lengths then compute it's mean, median and standard deviation. Normalize sepal length. After normalization, calculate the mean, median and standard deviation again.


In [8]:
input_file = './data/Iris.csv'

In [13]:
# Lets check the data
!head ./data/Iris.csv

Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
1,5.1,3.5,1.4,0.2,Iris-setosa
2,4.9,3.0,1.4,0.2,Iris-setosa
3,4.7,3.2,1.3,0.2,Iris-setosa
4,4.6,3.1,1.5,0.2,Iris-setosa
5,5.0,3.6,1.4,0.2,Iris-setosa
6,5.4,3.9,1.7,0.4,Iris-setosa
7,4.6,3.4,1.4,0.3,Iris-setosa
8,5.0,3.4,1.5,0.2,Iris-setosa
9,4.4,2.9,1.4,0.2,Iris-setosa


In [16]:
# Load the data. Since, ndarrays are homogeneous we skip the header row and the Species column. Also, we skip the Id column as it just represents the row number
irises = np.loadtxt(fname=input_file, delimiter=',', skiprows=1, usecols=(1,2,3,4))

In [18]:
irises[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [19]:
print(irises.shape)

(150, 4)


In [23]:
# Sepal length will have the index 0 on axis 1 in the ndarray
sepal_length = irises[:,1]
sepal_length[:10]

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1])

In [25]:
mu, med, sd = np.mean(sepal_length), np.median(sepal_length), np.std(sepal_length)
print(mu, med, sd)

3.0540000000000003 3.0 0.4321465800705435


In [27]:
Smax, Smin = sepal_length.max(), sepal_length.min()
S = (sepal_length - Smin)/(Smax - Smin)
S[:10]

array([0.625     , 0.41666667, 0.5       , 0.45833333, 0.66666667,
       0.79166667, 0.58333333, 0.58333333, 0.375     , 0.45833333])

In [28]:
mu, med, sd = np.mean(S), np.median(S), np.std(S)
print(mu, med, sd)

0.43916666666666665 0.41666666666666663 0.1800610750293931


More on Numpy Input Output:
- https://www.w3resource.com/numpy/input-and-output/index.php
- https://www.pythonpool.com/numpy-read-csv/